default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    # build_app(scheme: "FoodNutriVerse") # Uncomment if you want fastlane to build the app
    upload_to_app_store(submit_for_review: false)
  end

  desc "Upload metadata only (Screenshots, Description, Keywords)"
  lane :upload_metadata do
    deliver(
      skip_binary_upload: true,
      skip_screenshots: false,
      force: true # Skip HTML report verification
    )
  end
  
  desc "Download metadata from App Store"
  lane :download_metadata do
    deliver(
      download_screenshots: true,
      skip_binary_upload: true
    )
  end
end
